import re

from groq import Groq
from config import GROQ_API_KEY, LLM_MODEL

_client = Groq(api_key=GROQ_API_KEY)

_SYSTEM_PROMPT = (
    "You are a forensic text analyst. Judge whether the text was written by a human "
    "or generated by an AI language model. Consider voice, idiosyncrasy, coherence, "
    "and hedging. Respond in exactly two lines:\n"
    "Verdict: <AI or HUMAN>\n"
    "Score: <a number from 0.0 to 1.0 = probability the text is AI-generated>"
)

_NEUTRAL = 0.5


def _call_groq(text: str) -> str:
    resp = _client.chat.completions.create(
        model=LLM_MODEL,
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )
    return resp.choices[0].message.content


def _parse_score(raw: str) -> float | None:
    for line in raw.splitlines():
        if line.strip().lower().startswith("score:"):
            m = re.search(r"[-+]?\d*\.?\d+", line.split(":", 1)[1])
            if m:
                return max(0.0, min(1.0, float(m.group())))
    return None


def llm_score(text: str) -> float:
    """Return P(AI) in [0,1] from the LLM signal. Fail toward neutral 0.5."""
    try:
        raw = _call_groq(text)
    except Exception:
        return _NEUTRAL
    parsed = _parse_score(raw)
    return parsed if parsed is not None else _NEUTRAL
